# Generated by Django 4.2.1 on 2023-08-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(verbose_name="入职时间")),
                ("money", models.CharField(max_length=16, verbose_name="金钱")),
                ("use", models.CharField(max_length=128, verbose_name="用途")),
            ],
        ),
    ]
